### ISSUE TITLE
Font files is not found

### ISSUE THREAD

**Issue by intelfike** [SMerrony/DasherG#2]
First executing is successful, but I failed for some reason.

## Error message

```
$ DasherG
2018/01/25 22:16:09 Could not open BDF font file <D410-b-12.bdf>, open D410-b-12.bdf: no such file or directory
```

**Comment by SMerrony** [comment]
The font file needs to be in the directory you run the executable from, that's causing the error.

The same applies to the icon image.

Perhaps I can make it look for the font/icon where the executable is...

**Comment by SMerrony** [comment]
PARTIALLY(!) Fixed by commit da2f248043c5ca1b63e94722ae456296d941ed94

**Comment by intelfike** [comment]
I executed under comannd.
This is automaticary install DasherG by `go get`.
It create binnary file in `$GOPAH/bin`.(very easy)

I want it, but can't.

## Commands
```
$ history
...
  823  go get github.com/SMerrony/DasherG
  824  DasherG
```

## Error message
```
$ DasherG
2018/01/26 09:43:23 Could not open BDF font file </home/itel/Projects/go/bin/D410-b-12.bdf>, open /home/itel/Projects/go/bin/D410-b-12.bdf: no such file or directory
```

If files is static, then may be fix by go-bindata.

**Comment by SMerrony** [comment]
OK - I understand the problem better now - thanks for the response.

I had not considered people simply using 'go get' :-)  (My workflow is more git clone; go build;...)

I will try to sort out using go-bindata today.

**Comment by SMerrony** [comment]
I _think_ I have fixed this now, both for the font and for the application icon.

Could you test it and let me know?

Thanks.

**Comment by intelfike** [comment]
Thank you for fixed.
Perfect fix.
